//
//  AirportData.swift
//  TravelMemory
//
//  Comprehensive IATA airport database with 400+ airports worldwide.
//  Includes regional, island, and smaller airports beyond major hubs.
//

import Foundation

extension AirportDatabase {
    static let expanded: [(code: String, city: String, name: String)] = [
        // UK & Ireland
        ("LHR", "London", "Heathrow"),
        ("LGW", "London", "Gatwick"),
        ("STN", "London", "Stansted"),
        ("LTN", "London", "Luton"),
        ("LCY", "London", "City"),
        ("SEN", "London", "Southend"),
        ("MAN", "Manchester", "Intl"),
        ("BHX", "Birmingham", "Intl"),
        ("BRS", "Bristol", "Intl"),
        ("EDI", "Edinburgh", "Intl"),
        ("GLA", "Glasgow", "Intl"),
        ("ABZ", "Aberdeen", "Intl"),
        ("LBA", "Leeds Bradford", "Intl"),
        ("NCL", "Newcastle", "Intl"),
        ("EMA", "East Midlands", "Intl"),
        ("CWL", "Cardiff", "Intl"),
        ("BFS", "Belfast", "Intl"),
        ("BHD", "Belfast", "City"),
        ("INV", "Inverness", "Intl"),
        ("SOU", "Southampton", "Intl"),
        ("EXT", "Exeter", "Intl"),
        ("NQY", "Newquay", "Cornwall"),
        ("JER", "Jersey", "Intl"),
        ("GCI", "Guernsey", "Intl"),
        ("IOM", "Isle of Man", "Ronaldsway"),
        ("DUB", "Dublin", "Intl"),
        ("SNN", "Shannon", "Intl"),
        ("ORK", "Cork", "Intl"),
        ("KNO", "Knock", "Ireland West"),
        
        // Portugal & Atlantic Islands
        ("LIS", "Lisbon", "Humberto Delgado"),
        ("OPO", "Porto", "Francisco Sá Carneiro"),
        ("FAO", "Faro", "Intl"),
        ("FNC", "Funchal", "Madeira"),
        ("PXO", "Porto Santo", "Intl"),
        ("PDL", "Ponta Delgada", "João Paulo II"),
        ("TER", "Terceira", "Lajes"),
        ("HOR", "Horta", "Intl"),
        ("PIX", "Pico", "Intl"),
        ("SMA", "Santa Maria", "Intl"),
        ("FLW", "Flores", "Intl"),
        ("GRW", "Graciosa", "Intl"),
        ("SJZ", "São Jorge", "Intl"),
        
        // Spain & Canary/Balearic Islands
        ("MAD", "Madrid", "Barajas"),
        ("BCN", "Barcelona", "El Prat"),
        ("AGP", "Málaga", "Costa del Sol"),
        ("PMI", "Palma de Mallorca", "Son Sant Joan"),
        ("ALC", "Alicante", "El Altet"),
        ("VLC", "Valencia", "Intl"),
        ("SVQ", "Seville", "San Pablo"),
        ("BIO", "Bilbao", "Intl"),
        ("SCQ", "Santiago de Compostela", "Lavacolla"),
        ("IBZ", "Ibiza", "Intl"),
        ("MAH", "Menorca", "Mahón"),
        ("TFS", "Tenerife", "Sur/Reina Sofía"),
        ("TFN", "Tenerife", "Norte"),
        ("LPA", "Gran Canaria", "Intl"),
        ("ACE", "Lanzarote", "César Manrique"),
        ("FUE", "Fuerteventura", "Intl"),
        ("SPC", "La Palma", "Intl"),
        ("GMZ", "La Gomera", "Intl"),
        ("VDE", "El Hierro", "Intl"),
        ("GRX", "Granada", "Federico García Lorca"),
        ("OVD", "Asturias", "Intl"),
        ("SDR", "Santander", "Seve Ballesteros"),
        ("XRY", "Jerez", "La Parra"),
        ("REU", "Reus", "Intl"),
        ("GRO", "Girona", "Costa Brava"),
        
        // France
        ("CDG", "Paris", "Charles de Gaulle"),
        ("ORY", "Paris", "Orly"),
        ("BVA", "Paris", "Beauvais"),
        ("NCE", "Nice", "Côte d'Azur"),
        ("LYS", "Lyon", "Saint-Exupéry"),
        ("MRS", "Marseille", "Provence"),
        ("TLS", "Toulouse", "Blagnac"),
        ("BOD", "Bordeaux", "Mérignac"),
        ("NTE", "Nantes", "Atlantique"),
        ("SXB", "Strasbourg", "Intl"),
        ("AJA", "Ajaccio", "Napoléon Bonaparte"),
        ("BIA", "Bastia", "Poretta"),
        ("FSC", "Figari", "Sud Corse"),
        ("CLY", "Calvi", "Sainte-Catherine"),
        ("MPL", "Montpellier", "Méditerranée"),
        ("LIL", "Lille", "Lesquin"),
        ("RNS", "Rennes", "Saint-Jacques"),
        ("BIQ", "Biarritz", "Pays Basque"),
        
        // Germany
        ("FRA", "Frankfurt", "Main"),
        ("MUC", "Munich", "Franz Josef Strauss"),
        ("BER", "Berlin", "Brandenburg"),
        ("DUS", "Düsseldorf", "Intl"),
        ("HAM", "Hamburg", "Helmut Schmidt"),
        ("CGN", "Cologne", "Bonn"),
        ("STR", "Stuttgart", "Intl"),
        ("HAJ", "Hanover", "Intl"),
        ("NUE", "Nuremberg", "Albrecht Dürer"),
        ("LEJ", "Leipzig", "Halle"),
        ("DTM", "Dortmund", "Intl"),
        ("FMM", "Memmingen", "Allgäu"),
        ("DRS", "Dresden", "Intl"),
        ("BRE", "Bremen", "Intl"),
        
        // Italy
        ("FCO", "Rome", "Fiumicino"),
        ("CIA", "Rome", "Ciampino"),
        ("MXP", "Milan", "Malpensa"),
        ("LIN", "Milan", "Linate"),
        ("BGY", "Milan", "Bergamo"),
        ("VCE", "Venice", "Marco Polo"),
        ("TSF", "Venice", "Treviso"),
        ("NAP", "Naples", "Capodichino"),
        ("BLQ", "Bologna", "Guglielmo Marconi"),
        ("PSA", "Pisa", "Galileo Galilei"),
        ("FLR", "Florence", "Peretola"),
        ("CTA", "Catania", "Fontanarossa"),
        ("PMO", "Palermo", "Falcone–Borsellino"),
        ("CAG", "Cagliari", "Elmas"),
        ("OLB", "Olbia", "Costa Smeralda"),
        ("AHO", "Alghero", "Fertilia"),
        ("BRI", "Bari", "Karol Wojtyła"),
        ("TRN", "Turin", "Caselle"),
        ("VRN", "Verona", "Villafranca"),
        ("TPS", "Trapani", "Birgi"),
        ("SUF", "Lamezia Terme", "Intl"),
        ("BDS", "Brindisi", "Papola Casale"),
        
        // Netherlands, Belgium, Luxembourg
        ("AMS", "Amsterdam", "Schiphol"),
        ("EIN", "Eindhoven", "Intl"),
        ("RTM", "Rotterdam", "The Hague"),
        ("GRQ", "Groningen", "Eelde"),
        ("MST", "Maastricht", "Aachen"),
        ("BRU", "Brussels", "Zaventem"),
        ("CRL", "Brussels", "Charleroi"),
        ("ANR", "Antwerp", "Intl"),
        ("LUX", "Luxembourg", "Findel"),
        
        // Switzerland & Austria
        ("ZRH", "Zurich", "Kloten"),
        ("GVA", "Geneva", "Cointrin"),
        ("BSL", "Basel", "Mulhouse"),
        ("BRN", "Bern", "Belp"),
        ("VIE", "Vienna", "Schwechat"),
        ("SZG", "Salzburg", "W.A. Mozart"),
        ("INN", "Innsbruck", "Kranebitten"),
        ("GRZ", "Graz", "Thalerhof"),
        ("KLU", "Klagenfurt", "Intl"),
        ("LNZ", "Linz", "Blue Danube"),
        
        // Scandinavia
        ("CPH", "Copenhagen", "Kastrup"),
        ("OSL", "Oslo", "Gardermoen"),
        ("ARN", "Stockholm", "Arlanda"),
        ("NYO", "Stockholm", "Skavsta"),
        ("GOT", "Gothenburg", "Landvetter"),
        ("HEL", "Helsinki", "Vantaa"),
        ("TMP", "Tampere", "Pirkkala"),
        ("TRD", "Trondheim", "Værnes"),
        ("BGO", "Bergen", "Flesland"),
        ("SVG", "Stavanger", "Sola"),
        ("TOS", "Tromsø", "Langnes"),
        ("BOO", "Bodø", "Intl"),
        ("KEF", "Reykjavik", "Keflavík"),
        ("RKV", "Reykjavik", "Domestic"),
        ("AKU", "Akureyri", "Intl"),
        ("BLL", "Billund", "Intl"),
        ("AAL", "Aalborg", "Intl"),
        ("MMX", "Malmö", "Sturup"),
        
        // Eastern Europe
        ("WAW", "Warsaw", "Chopin"),
        ("WMI", "Warsaw", "Modlin"),
        ("KRK", "Kraków", "John Paul II"),
        ("GDN", "Gdańsk", "Lech Wałęsa"),
        ("WRO", "Wrocław", "Copernicus"),
        ("KTW", "Katowice", "Pyrzowice"),
        ("PRG", "Prague", "Václav Havel"),
        ("BRQ", "Brno", "Tuřany"),
        ("BUD", "Budapest", "Ferenc Liszt"),
        ("DEB", "Debrecen", "Intl"),
        ("OTP", "Bucharest", "Henri Coandă"),
        ("CLJ", "Cluj-Napoca", "Intl"),
        ("TSR", "Timișoara", "Traian Vuia"),
        ("SOF", "Sofia", "Intl"),
        ("VAR", "Varna", "Intl"),
        ("BOJ", "Burgas", "Intl"),
        ("BEG", "Belgrade", "Nikola Tesla"),
        ("ZAG", "Zagreb", "Franjo Tuđman"),
        ("SPU", "Split", "Intl"),
        ("DBV", "Dubrovnik", "Intl"),
        ("PUY", "Pula", "Intl"),
        ("ZAD", "Zadar", "Intl"),
        ("LJU", "Ljubljana", "Jože Pučnik"),
        ("SKP", "Skopje", "Alexander the Great"),
        ("TIA", "Tirana", "Nënë Tereza"),
        ("TGD", "Podgorica", "Intl"),
        ("TIV", "Tivat", "Intl"),
        
        // Greece & Cyprus
        ("ATH", "Athens", "Eleftherios Venizelos"),
        ("SKG", "Thessaloniki", "Makedonia"),
        ("HER", "Heraklion", "Nikos Kazantzakis"),
        ("CHQ", "Chania", "Daskalogiannis"),
        ("RHO", "Rhodes", "Diagoras"),
        ("CFU", "Corfu", "Ioannis Kapodistrias"),
        ("JTR", "Santorini", "Intl"),
        ("JMK", "Mykonos", "Intl"),
        ("KGS", "Kos", "Hippocrates"),
        ("ZTH", "Zakynthos", "Solomos"),
        ("EFL", "Kefalonia", "Anna Pollatou"),
        ("SMI", "Samos", "Aristarchos"),
        ("LCA", "Larnaca", "Intl"),
        ("PFO", "Paphos", "Intl"),
        
        // Turkey
        ("IST", "Istanbul", "Intl"),
        ("SAW", "Istanbul", "Sabiha Gökçen"),
        ("ESB", "Ankara", "Esenboğa"),
        ("AYT", "Antalya", "Intl"),
        ("ADB", "Izmir", "Adnan Menderes"),
        ("DLM", "Dalaman", "Intl"),
        ("BJV", "Bodrum", "Milas"),
        ("TZX", "Trabzon", "Intl"),
        
        // Middle East
        ("DXB", "Dubai", "Intl"),
        ("AUH", "Abu Dhabi", "Zayed Intl"),
        ("SHJ", "Sharjah", "Intl"),
        ("DOH", "Doha", "Hamad"),
        ("BAH", "Bahrain", "Intl"),
        ("KWI", "Kuwait", "Intl"),
        ("MCT", "Muscat", "Intl"),
        ("AMM", "Amman", "Queen Alia"),
        ("BEY", "Beirut", "Rafic Hariri"),
        ("TLV", "Tel Aviv", "Ben Gurion"),
        ("RUH", "Riyadh", "King Khalid"),
        ("JED", "Jeddah", "King Abdulaziz"),
        
        // North America
        ("JFK", "New York", "John F. Kennedy"),
        ("EWR", "Newark", "Liberty"),
        ("LGA", "New York", "LaGuardia"),
        ("LAX", "Los Angeles", "Intl"),
        ("SFO", "San Francisco", "Intl"),
        ("ORD", "Chicago", "O'Hare"),
        ("MDW", "Chicago", "Midway"),
        ("ATL", "Atlanta", "Hartsfield-Jackson"),
        ("DFW", "Dallas", "Fort Worth"),
        ("MIA", "Miami", "Intl"),
        ("FLL", "Fort Lauderdale", "Hollywood"),
        ("BOS", "Boston", "Logan"),
        ("SEA", "Seattle", "Tacoma"),
        ("DEN", "Denver", "Intl"),
        ("LAS", "Las Vegas", "Harry Reid"),
        ("MCO", "Orlando", "Intl"),
        ("PHX", "Phoenix", "Sky Harbor"),
        ("IAD", "Washington", "Dulles"),
        ("DCA", "Washington", "Reagan"),
        ("MSP", "Minneapolis", "Saint Paul"),
        ("DTW", "Detroit", "Metro Wayne"),
        ("PHL", "Philadelphia", "Intl"),
        ("CLT", "Charlotte", "Douglas"),
        ("SAN", "San Diego", "Intl"),
        ("TPA", "Tampa", "Intl"),
        ("PDX", "Portland", "Intl"),
        ("IAH", "Houston", "George Bush"),
        ("HNL", "Honolulu", "Daniel K. Inouye"),
        ("ANC", "Anchorage", "Ted Stevens"),
        ("YYZ", "Toronto", "Pearson"),
        ("YUL", "Montréal", "Trudeau"),
        ("YVR", "Vancouver", "Intl"),
        ("YYC", "Calgary", "Intl"),
        ("YEG", "Edmonton", "Intl"),
        ("YOW", "Ottawa", "Macdonald-Cartier"),
        ("YHZ", "Halifax", "Stanfield"),
        ("YWG", "Winnipeg", "Richardson"),
        ("MEX", "Mexico City", "Benito Juárez"),
        ("CUN", "Cancún", "Intl"),
        ("GDL", "Guadalajara", "Miguel Hidalgo"),
        ("SJD", "San José del Cabo", "Intl"),
        ("PVR", "Puerto Vallarta", "Ordaz"),
        
        // Caribbean
        ("NAS", "Nassau", "Lynden Pindling"),
        ("MBJ", "Montego Bay", "Sangster"),
        ("KIN", "Kingston", "Norman Manley"),
        ("PUJ", "Punta Cana", "Intl"),
        ("SDQ", "Santo Domingo", "Las Américas"),
        ("SJU", "San Juan", "Luis Muñoz Marín"),
        ("BGI", "Bridgetown", "Grantley Adams"),
        ("POS", "Port of Spain", "Piarco"),
        ("AUA", "Aruba", "Queen Beatrix"),
        ("CUR", "Curaçao", "Hato"),
        ("SXM", "St Maarten", "Princess Juliana"),
        ("PTP", "Pointe-à-Pitre", "Pôle Caraïbes"),
        ("FDF", "Fort-de-France", "Aimé Césaire"),
        
        // South America
        ("GRU", "São Paulo", "Guarulhos"),
        ("GIG", "Rio de Janeiro", "Galeão"),
        ("BSB", "Brasília", "Intl"),
        ("CNF", "Belo Horizonte", "Confins"),
        ("SSA", "Salvador", "Deputado Luís Eduardo"),
        ("REC", "Recife", "Guararapes"),
        ("POA", "Porto Alegre", "Salgado Filho"),
        ("CWB", "Curitiba", "Afonso Pena"),
        ("FOR", "Fortaleza", "Pinto Martins"),
        ("EZE", "Buenos Aires", "Ezeiza"),
        ("AEP", "Buenos Aires", "Aeroparque"),
        ("SCL", "Santiago", "Arturo Merino Benítez"),
        ("LIM", "Lima", "Jorge Chávez"),
        ("BOG", "Bogotá", "El Dorado"),
        ("MDE", "Medellín", "José María Córdova"),
        ("CTG", "Cartagena", "Rafael Núñez"),
        ("UIO", "Quito", "Mariscal Sucre"),
        ("GYE", "Guayaquil", "José Joaquín de Olmedo"),
        ("CCS", "Caracas", "Simón Bolívar"),
        ("MVD", "Montevideo", "Carrasco"),
        ("ASU", "Asunción", "Silvio Pettirossi"),
        ("LPB", "La Paz", "El Alto"),
        ("VVI", "Santa Cruz", "Viru Viru"),
        
        // Africa
        ("CPT", "Cape Town", "Intl"),
        ("JNB", "Johannesburg", "O.R. Tambo"),
        ("DUR", "Durban", "King Shaka"),
        ("NBO", "Nairobi", "Jomo Kenyatta"),
        ("MBA", "Mombasa", "Moi"),
        ("DAR", "Dar es Salaam", "Julius Nyerere"),
        ("ZNZ", "Zanzibar", "Abeid Amani Karume"),
        ("ADD", "Addis Ababa", "Bole"),
        ("CAI", "Cairo", "Intl"),
        ("HRG", "Hurghada", "Intl"),
        ("SSH", "Sharm el-Sheikh", "Intl"),
        ("CMN", "Casablanca", "Mohammed V"),
        ("RAK", "Marrakech", "Menara"),
        ("TNG", "Tangier", "Ibn Battouta"),
        ("FEZ", "Fez", "Saïss"),
        ("TUN", "Tunis", "Carthage"),
        ("ALG", "Algiers", "Houari Boumédiène"),
        ("LOS", "Lagos", "Murtala Muhammed"),
        ("ABJ", "Abidjan", "Félix-Houphouët-Boigny"),
        ("ACC", "Accra", "Kotoka"),
        ("DSS", "Dakar", "Blaise Diagne"),
        ("MRU", "Mauritius", "SSR Intl"),
        ("RUN", "Réunion", "Roland Garros"),
        ("TNR", "Antananarivo", "Ivato"),
        ("SEZ", "Mahé", "Seychelles Intl"),
        
        // Asia
        ("SIN", "Singapore", "Changi"),
        ("HKG", "Hong Kong", "Intl"),
        ("NRT", "Tokyo", "Narita"),
        ("HND", "Tokyo", "Haneda"),
        ("KIX", "Osaka", "Kansai"),
        ("ICN", "Seoul", "Incheon"),
        ("GMP", "Seoul", "Gimpo"),
        ("TPE", "Taipei", "Taoyuan"),
        ("BKK", "Bangkok", "Suvarnabhumi"),
        ("DMK", "Bangkok", "Don Mueang"),
        ("HKT", "Phuket", "Intl"),
        ("CNX", "Chiang Mai", "Intl"),
        ("KUL", "Kuala Lumpur", "Intl"),
        ("PEN", "Penang", "Intl"),
        ("BKI", "Kota Kinabalu", "Intl"),
        ("CGK", "Jakarta", "Soekarno-Hatta"),
        ("DPS", "Bali", "Ngurah Rai"),
        ("MNL", "Manila", "Ninoy Aquino"),
        ("CEB", "Cebu", "Mactan"),
        ("SGN", "Ho Chi Minh City", "Tan Son Nhat"),
        ("HAN", "Hanoi", "Noi Bai"),
        ("DAD", "Da Nang", "Intl"),
        ("REP", "Siem Reap", "Angkor"),
        ("PNH", "Phnom Penh", "Intl"),
        ("RGN", "Yangon", "Intl"),
        ("CMB", "Colombo", "Bandaranaike"),
        ("MLE", "Malé", "Velana"),
        ("DEL", "Delhi", "Indira Gandhi"),
        ("BOM", "Mumbai", "Chhatrapati Shivaji"),
        ("BLR", "Bangalore", "Kempegowda"),
        ("MAA", "Chennai", "Intl"),
        ("CCU", "Kolkata", "Netaji Subhas Chandra Bose"),
        ("HYD", "Hyderabad", "Rajiv Gandhi"),
        ("COK", "Kochi", "Intl"),
        ("GOI", "Goa", "Manohar Intl"),
        ("KTM", "Kathmandu", "Tribhuvan"),
        ("DAC", "Dhaka", "Hazrat Shahjalal"),
        ("ISB", "Islamabad", "Intl"),
        ("KHI", "Karachi", "Jinnah"),
        ("LHE", "Lahore", "Allama Iqbal"),
        ("PEK", "Beijing", "Capital"),
        ("PKX", "Beijing", "Daxing"),
        ("PVG", "Shanghai", "Pudong"),
        ("SHA", "Shanghai", "Hongqiao"),
        ("CAN", "Guangzhou", "Baiyun"),
        ("SZX", "Shenzhen", "Bao'an"),
        ("CTU", "Chengdu", "Tianfu"),
        ("CKG", "Chongqing", "Jiangbei"),
        ("XMN", "Xiamen", "Gaoqi"),
        ("WUH", "Wuhan", "Tianhe"),
        ("HGH", "Hangzhou", "Xiaoshan"),
        ("ULN", "Ulaanbaatar", "Chinggis Khaan"),
        ("TAS", "Tashkent", "Islam Karimov"),
        ("ALA", "Almaty", "Intl"),
        ("NQZ", "Astana", "Nursultan Nazarbayev"),
        ("GYD", "Baku", "Heydar Aliyev"),
        ("TBS", "Tbilisi", "Shota Rustaveli"),
        ("EVN", "Yerevan", "Zvartnots"),
        
        // Oceania
        ("SYD", "Sydney", "Kingsford Smith"),
        ("MEL", "Melbourne", "Tullamarine"),
        ("BNE", "Brisbane", "Intl"),
        ("PER", "Perth", "Intl"),
        ("ADL", "Adelaide", "Intl"),
        ("CNS", "Cairns", "Intl"),
        ("OOL", "Gold Coast", "Coolangatta"),
        ("AKL", "Auckland", "Intl"),
        ("CHC", "Christchurch", "Intl"),
        ("WLG", "Wellington", "Intl"),
        ("ZQN", "Queenstown", "Intl"),
        ("NAN", "Nadi", "Intl"),
        ("PPT", "Papeete", "Faa'a"),
        ("NOU", "Nouméa", "La Tontouta"),
    ]
}
